version: '3.9'

services:
  db:
    image: postgres:16
    container_name: auroville_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - auroville_network
    command: postgres -c shared_buffers=256MB -c work_mem=16MB -c maintenance_work_mem=128MB -c max_connections=50
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: app
    container_name: auroville_app
    depends_on:
          - db
    environment:
          DATABASE_URL: ${DATABASE_URL}
          NODE_ENV: ${NODE_ENV}
          HOST: ${HOST}
          PORT: ${PORT}
          NODE_OPTIONS: ${NODE_OPTIONS}
          JWT_SECRET: ${JWT_SECRET}
          SMTP_SERVER: ${SMTP_SERVER}
          SMTP_PORT: ${SMTP_PORT}
          SMTP_USERNAME: ${SMTP_USERNAME}
          SMTP_PASSWORD: ${SMTP_PASSWORD}
          SMTP_AUTH: ${SMTP_AUTH}
    volumes:
      - ./logs:/app/server/logs
    networks:
      - auroville_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "--max-time", "3", "--ipv4", "http://127.0.0.1:5000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
      target: nginx
    container_name: auroville_nginx
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/lib/letsencrypt:/var/lib/letsencrypt
    networks:
      - auroville_network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          memory: 256M
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  postgres_data:
  static_assets:
    driver: local
  letsencrypt:
  letsencrypt_data:

networks:
  auroville_network:
    driver: bridge
