import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { CacheFirst, NetworkFirst, StaleWhileRevalidate } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';

// Clean up old caches
cleanupOutdatedCaches();

// Precache all assets generated by vite with improved error handling
try {
  const precacheList = self.__WB_MANIFEST || [];
  precacheAndRoute(precacheList.filter(entry => {
    // Additional filtering to prevent caching problematic resources
    return entry && entry.url && !entry.url.includes('undefined');
  }));
  console.log('Precache list:', precacheList); // Log precacheList
  const filteredPrecacheList = precacheList.filter(entry => {
    return entry && entry.url && !entry.url.includes('undefined');
  });
  console.log('Filtered precache list:', filteredPrecacheList); // Log filteredPrecacheList
} catch (error) {
  console.error('Precaching failed:', error);
}

// Cache images with a Cache First strategy
registerRoute(
  ({ url }) => url.pathname.startsWith('/auroimgs/'),
  new CacheFirst({
    cacheName: 'auroville-images',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 30 * 24 * 60 * 60, // 30 days
      }),
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
    ],
    async fetchDidFail({ request }) {
      console.error(`Failed to fetch ${request.url} for caching`);
    }
  })
);

// Cache static assets with a Stale While Revalidate strategy
registerRoute(
  ({ request }) => {
    return request.destination === 'script' ||
           request.destination === 'style' ||
           request.destination === 'font';
  },
  new StaleWhileRevalidate({
    cacheName: 'static-resources',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 50,
        maxAgeSeconds: 24 * 60 * 60, // 24 hours
      }),
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
    ],
    async fetchDidFail({ request }) {
      console.error(`Failed to fetch ${request.url} for caching`);
    }
  })
);

// Cache API requests with a Network First strategy
registerRoute(
  ({ url }) => url.pathname.startsWith('/api/'),
  new NetworkFirst({
    cacheName: 'api-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 50,
        maxAgeSeconds: 5 * 60, // 5 minutes
      }),
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
    ],
    networkTimeoutSeconds: 10,
    async fetchDidFail({ request }) {
      console.error(`Failed to fetch API request ${request.url}`);
    }
  })
);

// Enhanced error handling
self.addEventListener('error', (event) => {
  console.error('Service Worker error:', event.error);
});

self.addEventListener('unhandledrejection', (event) => {
  console.error('Unhandled promise rejection:', event.reason);
  // Prevent default error handling to avoid breaking the service worker
  event.preventDefault();
});

self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});

// Navigation requests with more robust handling
registerRoute(
  ({ request }) => request.mode === 'navigate',
  new NetworkFirst({
    cacheName: 'pages',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 50,
        maxAgeSeconds: 10 * 60 // 10 minutes
      })
    ],
    async fetchDidFail({ request }) {
      console.error(`Navigation request failed for ${request.url}`);
    }
  })
);

self.addEventListener('activate', (event) => {
  event.waitUntil(
    Promise.all([
      self.clients.claim(),
      caches.keys().then(cacheNames => {
        return Promise.all(
          cacheNames.map(cacheName => {
            // Only delete caches that are not current
            if (!cacheName.includes('auroville')) {
              return caches.delete(cacheName);
            }
          }).filter(Boolean)
        );
      })
    ]).catch(error => {
      console.error('Cache cleanup failed:', error);
    })
  );
});
